/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.alexeytereshchenko.guardian;

import org.gradle.api.Project;
import org.gradle.testfixtures.ProjectBuilder;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class GuardianExtensionPluginTest {
  @Test
  void pluginRegistersATask() {
    // Create a test project and apply the plugin
    Project project = ProjectBuilder.builder().build();
    project.getPlugins().apply("io.github.alexeytereshchenko.guardian");

    // Verify the result
    assertNotNull(project);
  }
}
