/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package io.github.alexeytereshchenko.guardian;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import org.gradle.testkit.runner.BuildResult;
import org.gradle.testkit.runner.GradleRunner;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.platform.commons.logging.Logger;
import org.junit.platform.commons.logging.LoggerFactory;

class GuardianPluginFunctionalTest {

  private final Logger LOG = LoggerFactory.getLogger(this.getClass());

  File projectDir;

  @Test
  void canRunTask() {
    // Run the build
    GradleRunner runner = GradleRunner.create();
    runner.forwardOutput();
    runner.withArguments("build");
    runner.withPluginClasspath();
    runner.withProjectDir(projectDir);
    BuildResult result = runner.build();
    String output = result.getOutput();

    System.out.println(output);

    // Verify the result
    assertNotNull(output);
  }

  private void writeString(File file, String string) throws IOException {
    try (Writer writer = new FileWriter(file)) {
      writer.write(string);
    }
  }

  @BeforeEach
  public void setup() {
    projectDir = new File("../testProject");
  }

  @AfterEach
  public void clean() {
    GradleRunner runner = GradleRunner.create();
    runner.forwardOutput();
    runner.withArguments("clean");
    runner.withPluginClasspath();
    runner.withProjectDir(projectDir);
    runner.build();
    LOG.info(() -> "clean test project");
  }
}
